# Generated by Django 6.0.4 on 2026-05-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hashed_pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_privacy_lock_enabled',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
